### ISSUE TITLE
Hit or Miss

### ISSUE THREAD

**Issue by TiaMarieG** [cr4ckp0t/AnnounceRare#39]
It's very hit or miss when the chat line appears for me to click on when a rare is available to be announced. I'll click on the rare and most of the time the option to announce doesn't appear, but the option to announce that the rare is dead will become available once the rare dies.

Also, If possible, please add an option similar to rare share where a separate box appears that I can click on rather than in my main chat window. I have my Main/Gen chat windows separated to reduce chat clutter and it becomes a bit annoying to constantly click between the two to share info.

**Comment by ihme** [comment]
I have this exact same problem except I have never seen the chat link pop up prior to rares death. I have tried targeting a rare before it is engaged and also while it is engaged. While I was out of combat and while I was in combat. Same result, nothing. No errors either. Chat link only pops up after the rare is dead and that is only sometimes.

**Comment by cr4ckp0t** [comment]
I suspect that the addon is aware that it is a rare you targeted, it's just chosen not to send the link due to throttling. If you turn on debugging via `/rare debug`, I suspect you will see that it is throttling.

**Comment by toktokeh** [comment]
Glad someone else brought this up cause I was too lazy to create an issue here on GitHub. Same problem. Option only appears in the chat when rare is dead. Turning on debugging didn't do anything.

**Comment by ihme** [comment]
@cr4ckp0t I did /rare debug and it worked (I was able to get the chat link while the rare was still alive) but what does this mean? You said it was due to throttling, so, what would be the solution?

**Comment by Oshinigami** [comment]
Came here to say I've got the exact same issue. Never have I seen it come up with the option to announce a rare until the rare is dead (no matter what I do, debugging also doesn't help) though someone else from General chat seems to have no issues on the same version (3.2.3). Only installed this addon as of this version.

**Comment by cr4ckp0t** [comment]
Turning on debugging is not meant to help the issue, it just enables more verbose messages to tell you what is happening that it does not do for most of the users. I am currently working on moving the throttle to actually sending the message to the chat, rather than on the chat link you use to send the message. This should resolve this issue. I think it is because the target changed event is firing too often, and triggering the throttle.

**Comment by cr4ckp0t** [comment]
I just pushed the update mentioned above to GitHub, so Curse should grab it and package it in the next few minutes. 3.2.4 is the version you're looking for to see if the fix works.

**Comment by toktokeh** [comment]
Unfortunately 3.2.4 did not fix the issue for me but appreciate the effort. Still only get the chat option when rare's dead.

**Comment by cr4ckp0t** [comment]
Just to make sure I'm clear, you do know that it will not send a chat link just by a rare/tracked mob appearing on your minimap. You have to actually target it. Just wanted to make sure.

**Comment by cr4ckp0t** [comment]
Also what is your locale?

**Comment by TiaMarieG** [comment]
Yeah, it still doesn't work for me either. Targeted numerous rares and it would still only give the option to announce once the rare was dead. No one else announced either if that means anything. Not sure if you have a lock where only x amount of people can announce in a given time

I live in PST/US

**Comment by toktokeh** [comment]
> Just to make sure I'm clear, you do know that it will not send a chat link just by a rare/tracked mob appearing on your minimap. You have to actually target it. Just wanted to make sure.

Yes, thankfully Korthia presents plenty of opportunities to test this daily 😀I consistently get the chat option only when the rare dies. Just as a sanity check, I disabled all my other addons today and killed some rares; same outcome. My locale is en/us. Thank you.

**Comment by cr4ckp0t** [comment]
To be honest, I'm really not sure what is (or isn't) going on with your installs. I am unable to reproduce any issues and we appear to be on the same WoW locale (enUS). You can try to completely reinstall the addon by deleting it from AddOns, as well as its SavedVariables from your WTF folder.

**Comment by TiaMarieG** [comment]
I did a completely fresh install when the newest version came out, but I'll try again.

**Comment by cr4ckp0t** [comment]
Does that include removing the saved variables?

I am adding extra debugging to the addon now to see if we can figure out what is going on. It will be released as a beta, so you will have to either manually install it from Curse, or set your install channel in whatever addon updater you use. I will reply when I have posted the beta version to Curse. You will still have to have debugging enabled in the addon.

**Comment by cr4ckp0t** [comment]
Alright so, I combed over the code and I _think_ (hope) I found the issue and fixed it. I just pushed 3.2.5 to GitHub, so Curse will have it packaged soon.

**Comment by cr4ckp0t** [comment]
I had to push 3.2.6 to Curse to fix a localization error.

**Comment by toktokeh** [comment]
Thank you, will give this update a try tonight and let you know.

**Comment by pavophobic** [comment]
Hello, I spent some time testing the new update that was pushed earlier today, and receiving the following LUA errors:

Message: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
Message: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
Time: Thu Jul 29 13:22:57 2021
Count: 1
Stack: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\AnnounceRare\AnnounceRare.lua"]:632: in function `?'
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
Message: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
Time: Thu Jul 29 13:23:17 2021
Count: 1
Stack: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\AnnounceRare\AnnounceRare.lua"]:632: in function `?'
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TargetNearestEnemy'
[string "TARGETNEARESTENEMY"]:2: in function <[string "TARGETNEARESTENEMY"]:1>

Locals: <none>

Locals: <none>
Time: Thu Jul 29 13:24:39 2021
Count: 2
Stack: Interface\AddOns\AnnounceRare\AnnounceRare.lua:632: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\AnnounceRare\AnnounceRare.lua"]:632: in function `?'
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

**Comment by toktokeh** [comment]
3.2.6 fixed the issue for me. Thank you! 😊 I'm not getting any lua errors like the person above me but I have an addon that suppresses lua errors so my experience shouldn't count.

**Comment by cr4ckp0t** [comment]
I am getting a Lua error that I am working on fixing now.

**Comment by cr4ckp0t** [comment]
Okay, 3.2.7 was pushed to GitHub to fix the Lua error.
